version: '3'
services:
  ldap:
    image: osixia/openldap:1.1.7

  925r:
    build:
      context: 925r
      dockerfile: Dockerfile
    command: bash -c "cd 925r && python manage.py migrate && python manage.py runserver 0.0.0.0:8000"
    container_name: 925r
    hostname: 925r
    expose:
      - "8000"
    ports:
      - "8888:8000"
    volumes:
      - .:/code
    depends_on:
      - ldap

  yayata:
    container_name: yayata
    hostname: yayata
    command: bash -c "ls"
    build:
      context: yayata
      dockerfile: tests/docker/yayata.Dockerfile
    working_dir: /code/yayata
    expose:
      - "8080"
    ports:
      - "8080:8080"
    volumes:
      - ./config.json:/code/src/static/cfg/config.json