apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: mysql
  name: mysql
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mysql
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: mysql
    spec:
      containers:
        - args:
            - mysqld
            - --character-set-server=utf8mb4
            - --collation-server=utf8mb4_unicode_ci
            - --wait_timeout=28800
            - --max_allowed_packet=128M
          env:
            - name: MYSQL_DATABASE
              value: '{{ tpl .Values.mysql.env.MYSQL_DATABASE . }}'
            - name: MYSQL_PASSWORD
              value: '{{ tpl .Values.mysql.env.MYSQL_PASSWORD . }}'
            - name: MYSQL_ROOT_PASSWORD
              value: '{{ tpl .Values.mysql.env.MYSQL_ROOT_PASSWORD . }}'
            - name: MYSQL_USER
              value: '{{ tpl .Values.mysql.env.MYSQL_USER . }}'
          name: mysql
          ports:
            - name: mysql
              containerPort: 3306
          image: '{{ .Values.mysql.image.repository }}:{{ .Values.mysql.image.tag }}'
      restartPolicy: Always

