apiVersion: batch/v1
kind: Job
metadata:
  name: minio-bucket-creation
spec:
  template:
    spec:
      containers:
        - name: mc
          image: quay.io/minio/mc:latest  # Use the MinIO Client image
          command: ["/bin/sh", "-c"]
          args:
            - |
              sleep 5
              mc alias set myminio http://minio:9000 minioadmin minioadmin
              mc admin user svcacct add myminio minioadmin --access-key "minio" --secret-key "minio123321"
              mc mb myminio/media
              mc anonymous set public myminio/media
      restartPolicy: OnFailure
