apiVersion: apps/v1
kind: Deployment 
metadata:
  labels:
    app: minio
  name: minio
spec:
  replicas: 1
  selector:
    matchLabels:
      app: minio
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: minio
    spec:
       containers:
         - name: minio
           image: quay.io/minio/minio:latest
           command:
           - bash
           - -c
           args:
           - minio server data/ --console-address ":9001"
           ports:
             - containerPort: 9000
             - containerPort: 9001
